"use client";

import { useState } from "react";
import type {
  AuthSession,
  Playlist,
  RoomMediaConnectionState,
  RoomMember,
  RoomSnapshot,
  TrackMeta
} from "@music-room/shared";
import { RoomStage } from "./RoomStage";
import { TrackListSection } from "./TrackListSection";
import { QueuePanel } from "./QueuePanel";
import { PlaylistPanel } from "./PlaylistPanel";
import { MembersPanel } from "./MembersPanel";
import { MeshStatusPanel } from "./MeshStatusPanel";
import type { AvailabilityEntry } from "./MeshStatusPanel";

type RoomDashboardViewProps = {
  roomSnapshot: RoomSnapshot;
  currentTrack: TrackMeta | null;
  currentTrackDuration: number;
  isPlaying: boolean;
  activeSession: AuthSession | null;
  host: RoomMember | undefined;
  canControlPlayback: boolean;
  canDeleteRoom: boolean;
  canReorderQueue: boolean;
  currentSourceOwnerNickname: string | null;
  uploadedTracks: Record<string, { objectUrl: string }>;
  connectedPeersCount: number;
  mediaConnectionState: RoomMediaConnectionState;
  mediaConnectedPeersCount: number;
  cachedTrackCount: number;
  playlists: Playlist[];
  availabilitySummary: AvailabilityEntry[];
  onCopyJoinCode: () => Promise<void>;
  onLeaveRoom: () => void;
  onDeleteRoom: () => void;
  onFilesSelected: (files: FileList | null) => Promise<void>;
  onAddToQueue: (trackId: string) => Promise<void>;
  onPlayTrack: (trackId: string) => Promise<void>;
  onPlayQueueItem: (queueItemId: string) => Promise<void>;
  onRemoveQueueItem: (queueItemId: string) => Promise<void>;
  onReorderQueue: (queueItemIds: string[]) => Promise<void>;
  onSavePlaylistFromQueue: (title: string) => Promise<void>;
  onLoadPlaylistIntoRoom: (playlistId: string) => Promise<void>;
  onUpdatePlaylistTitle: (playlistId: string, title: string) => Promise<void>;
  onDeletePlaylist: (playlistId: string) => Promise<void>;
};

type TabId = "queue" | "library" | "members";

export function RoomDashboardView({
  roomSnapshot,
  currentTrack,
  currentTrackDuration,
  isPlaying,
  activeSession,
  host,
  canControlPlayback,
  canDeleteRoom,
  canReorderQueue,
  currentSourceOwnerNickname,
  uploadedTracks,
  connectedPeersCount,
  mediaConnectionState,
  mediaConnectedPeersCount,
  cachedTrackCount,
  playlists,
  availabilitySummary,
  onCopyJoinCode,
  onLeaveRoom,
  onDeleteRoom,
  onFilesSelected,
  onAddToQueue,
  onPlayTrack,
  onPlayQueueItem,
  onRemoveQueueItem,
  onReorderQueue,
  onSavePlaylistFromQueue,
  onLoadPlaylistIntoRoom,
  onUpdatePlaylistTitle,
  onDeletePlaylist
}: RoomDashboardViewProps) {
  const [activeTab, setActiveTab] = useState<TabId>("queue");
  const canCreatePlaylist = roomSnapshot.queue.length > 0;

  return (
    <div className="flex flex-col lg:flex-row w-full h-[calc(100vh-140px)] relative overflow-hidden">
      {/* Background Ambience generated by Now Playing */}
      <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none">
         {isPlaying && (
           <div className="absolute top-1/4 left-1/4 w-[50vw] h-[50vw] bg-accent/5 rounded-full blur-[100px] animate-pulse pointer-events-none" />
         )}
      </div>

      {/* LEFT PANE: The Stage */}
      <div className="w-full h-full lg:w-[55%] xl:w-[60%] flex flex-col relative z-10 shrink-0">
        <RoomStage
          roomSnapshot={roomSnapshot}
          currentTrack={currentTrack}
          currentTrackDuration={currentTrackDuration}
          isPlaying={isPlaying}
          activeSession={activeSession}
          host={host}
          canDeleteRoom={canDeleteRoom}
          currentSourceOwnerNickname={currentSourceOwnerNickname}
          mediaConnectionState={mediaConnectionState}
          mediaConnectedPeersCount={mediaConnectedPeersCount}
          onCopyJoinCode={onCopyJoinCode}
          onLeaveRoom={onLeaveRoom}
          onDeleteRoom={onDeleteRoom}
        />
      </div>

      {/* RIGHT PANE: The Collaboration Hub */}
      <div className="flex-1 w-full flex flex-col relative z-20 bg-black/40 lg:bg-[#050505]/80 backdrop-blur-2xl lg:border-l border-white/5 lg:shadow-[-20px_0_50px_rgba(0,0,0,0.5)] h-full min-h-0 rounded-t-3xl lg:rounded-none lg:rounded-tl-3xl">
        
        {/* Hub Header & Tabs */}
        <div className="sticky top-0 z-30 pt-6 px-6 pb-2 border-b border-white/5 bg-gradient-to-b from-[#050505] to-transparent shrink-0">
           <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-bold tracking-widest text-white/80 uppercase font-mono">工作台 (Hub)</h3>
           </div>
           
           <div className="flex items-center gap-1 bg-white/5 p-1 rounded-lg w-full max-w-sm">
             {(["queue", "library", "members"] as TabId[]).map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`flex-1 text-xs font-semibold py-1.5 rounded-md transition-all ${
                    activeTab === tab 
                      ? "bg-white/10 text-white shadow-sm" 
                      : "text-white/50 hover:text-white/80 hover:bg-white/5"
                  }`}
                >
                  {tab === "queue" ? "共享队列" : tab === "library" ? "我的曲库" : "成员与状态"}
                </button>
             ))}
           </div>
        </div>

        {/* Hub Content Area - Scrollable */}
        <div className="flex-1 overflow-y-auto w-full p-6 custom-scrollbar pb-32">
           {activeTab === "queue" && (
             <div className="flex flex-col w-full animate-fade-in gap-8">
               <QueuePanel
                  queue={roomSnapshot.queue}
                  tracks={roomSnapshot.tracks}
                  currentTrackId={roomSnapshot.room.playback.currentTrackId ?? null}
                  activeSession={activeSession}
                  hostId={roomSnapshot.room.hostId}
                  canControlPlayback={canControlPlayback}
                  canReorderQueue={canReorderQueue}
                  onPlayQueueItem={onPlayQueueItem}
                  onRemoveQueueItem={onRemoveQueueItem}
                  onReorderQueue={onReorderQueue}
                  onAddToQueue={onAddToQueue}
                />
             </div>
           )}

           {activeTab === "library" && (
             <div className="flex flex-col w-full animate-fade-in gap-8">
                <TrackListSection
                  tracks={roomSnapshot.tracks}
                  uploadedTracks={uploadedTracks}
                  canControlPlayback={canControlPlayback}
                  onFilesSelected={onFilesSelected}
                  onAddToQueue={onAddToQueue}
                  onPlayTrack={onPlayTrack}
                />
                
                <div className="h-px w-full bg-white/5 my-4 shrink-0" />
                
                <PlaylistPanel
                  playlists={playlists}
                  activeSession={activeSession}
                  canCreatePlaylist={canCreatePlaylist}
                  onSavePlaylistFromQueue={onSavePlaylistFromQueue}
                  onLoadPlaylistIntoRoom={onLoadPlaylistIntoRoom}
                  onUpdatePlaylistTitle={onUpdatePlaylistTitle}
                  onDeletePlaylist={onDeletePlaylist}
                />
             </div>
           )}

           {activeTab === "members" && (
             <div className="flex flex-col w-full animate-fade-in gap-8">
                <MembersPanel members={roomSnapshot.room.members} />
                
                <div className="h-px w-full bg-white/5 my-4 shrink-0" />
                
                <MeshStatusPanel
                  availabilitySummary={availabilitySummary}
                  connectedPeersCount={connectedPeersCount}
                  cachedTrackCount={cachedTrackCount}
                />
             </div>
           )}
        </div>

      </div>
    </div>
  );
}
