upstream music_room_web {
  server web:3000;
}

upstream music_room_server {
  server server:3001;
}

# HTTP to HTTPS redirect.
server {
  listen 80;
  server_name ${APP_DOMAIN};
  client_max_body_size 200m;
  return 301 https://$$host$$request_uri;
}

server {
  listen 443 ssl;
  server_name ${APP_DOMAIN};
  client_max_body_size 200m;

  ssl_certificate     /etc/letsencrypt/live/${APP_DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${APP_DOMAIN}/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  include music-room.routes.conf;
}
