apiVersion: 1
datasources:
  - name: Music Room Prometheus
    uid: music-room-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
