"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import type { AdminIncident, AdminOverview, AdminRoomSummary, AdminSession, AdminUserSummary } from "@music-room/shared";
import { adminApi, AdminApiError } from "@/lib/admin-api";

type Tab = "overview" | "rooms" | "users" | "incidents" | "audit" | "system";
type AuditRow = { id: string; action: string; targetType: string; targetId: string | null; reason: string | null; result: string; createdAt: string };

export default function AdminPage() {
  const [tab, setTab] = useState<Tab>("overview");
  const [session, setSession] = useState<AdminSession | null>(null);
  const [overview, setOverview] = useState<AdminOverview | null>(null);
  const [rooms, setRooms] = useState<AdminRoomSummary[]>([]);
  const [users, setUsers] = useState<AdminUserSummary[]>([]);
  const [incidents, setIncidents] = useState<AdminIncident[]>([]);
  const [audit, setAudit] = useState<AuditRow[]>([]);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    try {
      setError(""); const current = session ?? await adminApi.session(); setSession(current);
      const [overviewData, roomData, userData, incidentData, auditData] = await Promise.all([adminApi.overview(), adminApi.rooms(query), adminApi.users(query), adminApi.incidents(), adminApi.audit()]);
      setOverview(overviewData); setRooms(roomData.data); setUsers(userData.data); setIncidents(incidentData.data); setAudit(auditData.data);
    } catch (cause) { if (cause instanceof AdminApiError && (cause.status === 401 || cause.status === 403)) { window.location.assign("/admin/login"); return; } setError(cause instanceof Error ? cause.message : "管理数据加载失败。"); }
  }, [query, session]);
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === "visible") void load(); }, tab === "overview" ? 5000 : 10000); return () => window.clearInterval(timer); }, [load, tab]);
  async function logout() { await adminApi.logout().catch(() => undefined); window.sessionStorage.removeItem("music-room-admin-csrf"); window.location.assign("/admin/login"); }
  const labels: Record<Tab, string> = { overview: "系统总览", rooms: "房间", users: "用户", incidents: "异常", audit: "审计", system: "系统" };
  const tabs: Tab[] = ["overview", "rooms", "users", "incidents", "audit", "system"];
  return <div className="min-h-screen bg-[#07080b] text-white"><header className="sticky top-0 z-20 border-b border-white/[0.08] bg-[#07080b]/95"><div className="flex h-16 items-center justify-between px-4 lg:px-8"><div><div className="font-semibold">Music Room / Admin</div><div className="text-[11px] text-white/40">运营观测台</div></div><div className="flex items-center gap-3 text-sm text-white/60"><span>{session?.nickname ?? "管理员"}</span><button onClick={() => void load()} className="border border-white/10 px-3 py-1.5 text-xs hover:bg-white/10">刷新</button><button onClick={() => void logout()} className="border border-white/10 px-3 py-1.5 text-xs hover:bg-white/10">退出</button></div></div></header><div className="mx-auto flex max-w-[1500px] flex-col lg:flex-row"><nav className="flex gap-1 overflow-x-auto border-b border-white/[0.08] p-3 lg:w-52 lg:flex-col lg:border-b-0 lg:border-r lg:pt-8">{tabs.map(id => <button key={id} onClick={() => setTab(id)} className={"whitespace-nowrap px-3 py-2 text-left text-sm " + (tab === id ? "bg-[#0070f3] text-white" : "text-white/55 hover:bg-white/5")}>{labels[id]}</button>)}</nav><main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[0.2em] text-[#60a5fa]">CONTROL PLANE</p><h1 className="mt-2 text-3xl font-semibold">{labels[tab]}</h1></div>{tab === "rooms" || tab === "users" ? <input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索 ID、用户名或昵称" className="w-full border border-white/10 bg-transparent px-3 py-2 text-sm outline-none focus:border-[#0070f3] sm:w-72" /> : null}</div>{error ? <div className="mt-5 border border-red-400/20 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error} <button onClick={() => void load()} className="ml-3 underline">重试</button></div> : null}{tab === "overview" ? <Overview overview={overview} /> : tab === "rooms" ? <Rooms rooms={rooms} refresh={load} /> : tab === "users" ? <Users users={users} refresh={load} /> : tab === "incidents" ? <Incidents rows={incidents} /> : tab === "audit" ? <Audit rows={audit} /> : <System overview={overview} />}</main></div></div>;
}
function Overview({ overview }: { overview: AdminOverview | null }) { return <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="在线用户" value={overview?.users.online ?? 0} /><Metric label="活跃房间" value={overview?.rooms.active ?? 0} /><Metric label="正在播放" value={overview?.playback.active ?? 0} /><Metric label="打开异常" value={overview?.openIncidents ?? 0} /></div><section className="mt-8 border border-white/[0.08] p-5"><h2 className="text-sm font-medium">依赖状态</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Status label="PostgreSQL" value={overview?.dependencies.prisma} /><Status label="Redis" value={overview?.dependencies.redis} /><Status label="实例" value={String(overview?.instances ?? 0)} /></div></section></>; }
function Rooms({ rooms, refresh }: { rooms: AdminRoomSummary[]; refresh: () => Promise<void> }) { return <Table><thead><tr><Th>房间</Th><Th>健康</Th><Th>成员</Th><Th>播放</Th><Th>操作</Th></tr></thead><tbody>{rooms.map(room => <tr key={room.id}><Td><a href={"/admin/rooms/" + encodeURIComponent(room.id)} className="font-mono text-xs text-[#60a5fa] underline">{room.id}</a><div className="text-xs text-white/40">{room.joinCode}</div></Td><Td><Badge value={room.health} /></Td><Td>{room.onlineMemberCount}/{room.memberCount}</Td><Td>{room.playbackStatus}</Td><Td><button className="text-xs text-red-300 underline" onClick={async () => { const code = window.prompt("输入当前房间码"); const reason = window.prompt("终止原因（至少 8 字）"); if (code && reason && window.confirm("确认永久结束此房间？")) { await adminApi.terminateRoom(room.id, code, reason); await refresh(); } }}>永久结束</button></Td></tr>)}</tbody></Table>; }
function Users({ users, refresh }: { users: AdminUserSummary[]; refresh: () => Promise<void> }) { return <Table><thead><tr><Th>用户</Th><Th>状态</Th><Th>会话</Th><Th>最近登录</Th><Th>操作</Th></tr></thead><tbody>{users.map(user => <tr key={user.id}><Td><div>{user.nickname}</div><div className="text-xs text-white/40">{user.username}</div></Td><Td><Badge value={user.status.toLowerCase()} /></Td><Td>{user.activeSessionCount}</Td><Td className="text-xs text-white/50">{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : "未登录"}</Td><Td>{user.role === "USER" ? <div className="flex gap-3 text-xs"><button className="underline" onClick={async () => { const reason = window.prompt("操作原因（至少 8 字）"); if (reason && window.confirm("确认修改账号状态？")) { await adminApi.setUserStatus(user.id, user.status === "ACTIVE" ? "DISABLED" : "ACTIVE", reason); await refresh(); } }}>{user.status === "ACTIVE" ? "禁用" : "启用"}</button><button className="text-amber-200 underline" onClick={async () => { const reason = window.prompt("撤销原因（至少 8 字）"); if (reason && window.confirm("确认撤销全部普通会话？")) { await adminApi.revokeSessions(user.id, reason); await refresh(); } }}>撤销会话</button></div> : <span className="text-xs text-white/30">管理员</span>}</Td></tr>)}</tbody></Table>; }
function Incidents({ rows }: { rows: AdminIncident[] }) { return <Table><thead><tr><Th>级别</Th><Th>类型</Th><Th>范围</Th><Th>状态</Th><Th>最近发生</Th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><Td><Badge value={row.severity.toLowerCase()} /></Td><Td>{row.type}</Td><Td className="font-mono text-xs">{row.scopeType}:{row.scopeId ?? "-"}</Td><Td>{row.status}</Td><Td className="text-xs text-white/50">{new Date(row.lastSeenAt).toLocaleString()}</Td></tr>)}</tbody></Table>; }
function Audit({ rows }: { rows: AuditRow[] }) { return <Table><thead><tr><Th>时间</Th><Th>动作</Th><Th>目标</Th><Th>结果</Th><Th>原因</Th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><Td className="text-xs text-white/50">{new Date(row.createdAt).toLocaleString()}</Td><Td>{row.action}</Td><Td className="font-mono text-xs">{row.targetType}:{row.targetId ?? "-"}</Td><Td>{row.result}</Td><Td className="max-w-md text-xs text-white/50">{row.reason ?? "-"}</Td></tr>)}</tbody></Table>; }
function System({ overview }: { overview: AdminOverview | null }) { return <div className="mt-8 grid gap-4 md:grid-cols-2"><Status label="PostgreSQL" value={overview?.dependencies.prisma} /><Status label="Redis" value={overview ? overview.dependencies.redis + " (" + overview.dependencies.redisMode + ")" : undefined} /><Status label="实例" value={String(overview?.instances ?? 0)} /><Status label="生成时间" value={overview?.generatedAt ? new Date(overview.generatedAt).toLocaleString() : undefined} /></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="border-l border-white/10 px-4 py-3"><p className="text-xs text-white/45">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function Status({ label, value }: { label: string; value?: string }) { return <div className="flex items-center justify-between border border-white/[0.08] px-4 py-3"><span className="text-sm text-white/70">{label}</span><span className="font-mono text-xs text-white/50">{value ?? "unknown"}</span></div>; }
function Badge({ value }: { value: string }) { const color = value.includes("critical") || value.includes("disabled") ? "text-red-300" : value.includes("degraded") ? "text-amber-300" : "text-emerald-300"; return <span className={"font-mono text-xs uppercase " + color}>{value}</span>; }
function Table({ children }: { children: ReactNode }) { return <div className="mt-8 overflow-x-auto border border-white/[0.08]"><table className="w-full min-w-[760px] text-left text-sm">{children}</table></div>; }
function Th({ children }: { children: ReactNode }) { return <th className="border-b border-white/[0.08] px-4 py-3 text-xs font-medium text-white/45">{children}</th>; }
function Td({ children, className = "" }: { children: ReactNode; className?: string }) { return <td className={"border-b border-white/[0.06] px-4 py-3 " + className}>{children}</td>; }
